### ISSUE TITLE
unexpected eval behavior

### ISSUE THREAD

**Issue by et2010** [abo-abo/lpy#12]
Eval following expression with `2e`:

```
(5.94 + 4.36) / 2
```

expected behavior:

```
(5.94 + 4.36) / 2
#  => 5.15
```

actual behavior:

```
(5.94 + 4.36)
#  => 5.15
/ 2
```

The `/ 2` was below the output after the evaluation. Any ideas?

**Comment by abo-abo** [comment]
Thanks for the report, it's reproducible. I'll fix it in the evening when I have some free time.

**Comment by abo-abo** [comment]
Please test.

**Comment by et2010** [comment]
It works great! Thanks!
