### ISSUE TITLE
lispy-describe-inline doesn't work when parentheses are present

### ISSUE THREAD

**Issue by et2010** [abo-abo/lpy#18]
For example, the following case  does work:

![image](https://user-images.githubusercontent.com/11584902/46147659-ac84c500-c298-11e8-9875-ebffffc2d17d.png)

But when parentheses are present, it doesn't work any longer:

![image](https://user-images.githubusercontent.com/11584902/46147736-e950bc00-c298-11e8-8292-d87c41de6838.png)

or

![image](https://user-images.githubusercontent.com/11584902/46147770-04bbc700-c299-11e8-817c-ecdef4acca07.png)

**Comment by abo-abo** [comment]
Thanks, please test. It's still a bit off, mostly due to the fact that you'll get a docstring based either on static analysis (Jedi) or on REPL state, depending on point position. But it works for my test case.

**Comment by et2010** [comment]
Thanks for the fix! It works great.
