### ISSUE TITLE
Space auto-inserted around '=' in keyword arguments

### ISSUE THREAD

**Issue by subhacom** [abo-abo/lpy#21]
When assigning values to keyword arguments in a function call lpy automatically inserts spaces around the = operator. This goes against pep8 recommendation.

**Comment by abo-abo** [comment]
Please add a reproduction scenario. I was able to input this in a straightforward way:

```python
temp(x=1, y=2)
```

**Comment by guibor** [comment]
For me this is always the case - space is always inserted around "=". This seems to be the "soap-default-action" when "=" is entered.

**Comment by abo-abo** [comment]
Thanks. Sorry, I was using an up-to date soap.el, which this repo included an outdated version. Please test.

**Comment by guibor** [comment]
This worked, thanks!
