### ISSUE TITLE
Allow switching to standard Python shell

### ISSUE THREAD

**Issue by guibor** [abo-abo/lpy#24]
Currently lpy filters only processes with particular names starting with lispy-python-* - this limits the ability to attach to shells started with other Python frameworks that can be used in parallel.

**Comment by abo-abo** [comment]
Thanks. <kbd>xp</kbd> now works for shells started with `run-python`. You can customize `lispy-python-process-regexes` to make the other shells work.

**Comment by guibor** [comment]
Thanks a lot!

By the way, this package is absolutely outstanding - brilliant beyond
belief!
