### ISSUE TITLE
A warning about lpy-switch-to-shell

### ISSUE THREAD

**Issue by firslov** [abo-abo/lpy#25]
when C-c C-z, the emacs shows me this:
/anaconda3/bin/ipython:1: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  #!/anaconda3/bin/python

And the ipython is always started with cell [2] instead of [1], this is really upsetting.

**Comment by abo-abo** [comment]
Thanks, please test.
