### ISSUE TITLE
lpy-slurp and lpy-barf print weird characters

### ISSUE THREAD

**Issue by guibor** [abo-abo/lpy#26]
Specifically, 

^[x

**Comment by abo-abo** [comment]
Thanks. I see now that `lpy-slurp` and `lpy-barf` should bound to keys.

**Comment by guibor** [comment]
I still get this weird sequence ^[x when I call soap-command (instead of lpy-slurp and lpy-barf)

**Comment by guibor** [comment]
(and again I wanted to say thank you for this wonderful package)

**Comment by abo-abo** [comment]
It's likely that the issue is in your config. Can you reproduce with `emacs -Q`?

I've added some scripts to make it easier:

```elisp
sudo pip3 install pycook
cook deps
cook plain
```

**Comment by abo-abo** [comment]
Do you have the `jedi` Python module installed? What happens if eval:

```python
import imp
lp=imp.load_source("/path-to/lispy/lispy-python.py")
```

**Comment by abo-abo** [comment]
What happens if you turn off `lpy-mode` and do `<f1> k >`?

**Comment by guibor** [comment]
Reg. jedi -- I do have it installed (am able to import jedi)

If I run the line above, I get:

TypeError: load_source() takes at least 2 arguments (1 given)

I think I know what to do about it though, I wonder if this isn't a python version issue

**Comment by guibor** [comment]
I can do:

lp = imp.load_source(
    'lp',
    '~/.emacs.d/elpa/develop/lispy-20191016.1250/lispy-python.py'
)

In this case, I'm able to evaluate expressions at will, but assignments work but crash the shell (becomes read-only -- let: Text is read-only)

**Comment by guibor** [comment]
As for what ">" does, I get
"""
> runs the command outshine-self-insert-command (found in outshine-mode-map),
  which is an interactive Lisp function in ‘outshine.el’.
"""
Doesn't lpy work with outshine?

**Comment by abo-abo** [comment]
OK, does `cook plain` produce a running Emacs? What the system and Emacs version? What happens when you press `>` in `python-mode`?

**Comment by guibor** [comment]
cook plain produces a wroking emacs with an error - Error (use-package): Cannot load jedi

">" in python-mode just produces ">" (whether in my setup or in the one spawned by running "cook plain").

**Comment by abo-abo** [comment]
Is this the output of `cook deps`?

```
~/.elpa/26.3/elpa
Package refresh done
company: OK
jedi: OK
company-jedi: OK
lispy: OK
use-package: OK
```

Check `~/.elpa/26.3/elpa`. Is `jedi-20191011.1750` and `jedi-core-20191011.1750` there?

> ">" in python-mode just produces ">"

But the one from `cook plain` produces `python-mode` with `lpy-mode` on. So `F1 k >` there should tell you that it's bound to `soap-command`. Is that true?

**Comment by guibor** [comment]
Output of cook deps is:

Importing package-keyring.gpg...
Importing package-keyring.gpg...done
Contacting host: melpa.org:80
Contacting host: melpa.org:80
Contacting host: elpa.gnu.org:80
Package refresh done
company: OK
jedi: OK
company-jedi: OK
lispy: OK
use-package: OK
Setting `package-selected-packages' temporarily since "emacs -q" would overwrite customizations
No packages to upgrade.
All packages up to date

**Comment by abo-abo** [comment]
OK, let's try to fix just the soap.el issue first. Try:

```
emacs -Q -l soap.el
```

In `*scratch*`:

```elisp
(require 'python)
(define-key python-mode-map ">" 'soap-command)
(define-key python-mode-map "<" 'soap-command)
```

Open a Python buffer and check what `>` and `<` do.

**Comment by guibor** [comment]
They are indeed bound to soap command, but instead slurping/barfing they now just insert themselves (" < " or " >")

**Comment by abo-abo** [comment]
OK, so now you need to isolate the part of your config that's responsible for the weird character. Since it works as intended with `emacs -Q`.

**Comment by guibor** [comment]
Also, I'm generally curious how 

import imp
lp=imp.load_source("/path-to/lispy/lispy-python.py")

works for you, since load_source is supposed to receive two arguments

**Comment by abo-abo** [comment]
@guibor

It should be:

```python
lp=imp.load_source('lispy-python', "/path-to/lispy/lispy-python.py")
```

**Comment by guibor** [comment]
And yet lispy--python-middleware-load in lispy uses:

```
 (r (lispy--eval-python
               (format
                (concat
                 "try:\n"
                 "    from importlib.machinery import SourceFileLoader\n"
                 "    lp=SourceFileLoader(%s).load_module()\n"
                 "except:\n"
                 "    import imp;lp=imp.load_source(%s)\n"
                 "__name__='__repl__';"
                 "pm=lp.Autocall(lp.pm);")
                module-path module-path))))
```

**Comment by abo-abo** [comment]
That's not the case. Here `%s` is:

```elisp
"'lispy-python','/path-to-lispy/lispy-python.py'"
```

Did you manage to run `cook plain` so far? Can you verify that `>` and `<` work properly there?

**Comment by guibor** [comment]
I don't have this issue anymore (not sure what solved it, but was probably an issue with my own setup).
