### ISSUE TITLE
Soap dependency

### ISSUE THREAD

**Issue by noctuid** [abo-abo/lpy#3]
Where can the soap package be found? I couldn't find a package that provides soap and defines soap-command.

**Comment by abo-abo** [comment]
It's not on MELPA yet, but neither is lpy:). I have it here: https://github.com/abo-abo/soap.

**Comment by noctuid** [comment]
Thanks. The idea of making special in the whitespace on indented lines is really interesting. Is this supposed replace the idea of using parens? It seems that lispy-mode and lpy-mode are incompatible (enabling lispy-mode breaks the whitespace/beginning of def functionality for me).

**Comment by abo-abo** [comment]
> It seems that lispy-mode and lpy-mode are incompatible

You're right. `lpy-mode` only should be used for Python. It depends on lispy mostly for eval.

**Comment by abo-abo** [comment]
> Is this supposed replace the idea of using parens?

Indentation is the poor man's parens. One advantage is that it's ubiquitous.
