### ISSUE TITLE
Very hard to understand

### ISSUE THREAD

**Issue by spiderbit** [abo-abo/lpy#32]
First I struggle with the concept that many things only work depending where your cursor is, and for some commands it makes sense for other not.

The biggest struggle and I am still not sure if I am correct was to realize that lispy-mode must be activated so that lpy-mode functions properly? I needed probably 1 hour to guess / try+error that alone.

Then maybe for a lispy-user all that stuff makes a lot of sense but for me that years ago looked over lispy with the result that it's not good enough / does not compete with paredit even with a far stretch after 30 mins trying to use it, didn't really get how I am supposed to use it.

I mean I am a paredit user so I know as example slurf / barf, something I enjoy and that seems to be implemented, but not as interactive commands instead slurf seems to be hidden in "split" which seems to work kind of, but then barf I have no idea how to make it work and looking over the source for minutes didn't make it that much clearer.

And then the shortcuts not only do you have to know where the cursor must exactly be or it just ignores your commands but you have to know which 20 shortcuts do what you want... that are not very intuitive and named in a way that also makes not much sense not to mention documentation.

Well I just looked at lispy-mode and that would probably better for me, but I still send this report back as feedback especially (if I am correct) to not mention that you need lispy mode active to make this mode work is really a big trap.

**Comment by abo-abo** [comment]
Please have a look again that the commentary section of lpy.el:

```elisp
;;; Commentary:
;;
;; This is an attempt to implement a variant of `lispy-mode'
;; (https://github.com/abo-abo/lispy) for Python.  Unfortunately,
;; Python isn't nearly as well-structured as LISP.  But Python is
;; ubiquitous, and the less powerful `lpy-mode' is better than nothing
;; at all.
;;
;; The basic idea of `lpy-mode' is to increase the editing efficiency
;; by binding useful navigation, refactoring and evaluation commands
;; to unprefixed keys, e.g. "j" or "e".  But only in certain point
;; positions, so that you are still able to use uprefixed keys to
;; insert themselves.
```

This commentary is replicated [on MELPA](https://melpa.org/#/lpy) as well.
