### ISSUE TITLE
Outline imcompatible with PEP8 stype E265

### ISSUE THREAD

**Issue by rhymer** [abo-abo/lpy#4]
The outline in lpy is
`#* Level 1`
However this does not comply with pep8 E265: Block comments should have a space after #.
Does it make sense to change it to something like
`# * Level 1` 
to please the linter? Thanks.

**Comment by abo-abo** [comment]
I find the current style more aesthetically pleasing.

But if many users prefer to satisfy E265, I'd accept a PR that updates `lpy-font-lock-keywords` and `outline-regexp`.

**Comment by rhymer** [comment]
Thanks @abo-abo; I do agree that
`#* Level 1` ...(1)
looks nicer than
`# * Level1` ...(2)
How about providing options for user to choose between (1) and (2)? Thanks!
