### ISSUE TITLE
How to make lpy work with evil?

### ISSUE THREAD

**Issue by et2010** [abo-abo/lpy#7]
I googled but found nothing on this topic. Any suggestions? Thanks!

**Comment by abo-abo** [comment]
Just as with `lispy` or `worf`, you can make `evil` work by having `lpy` active only in the insert mode and not in normal mode.

Try looking at how `lispyville` by @noctuid does it.

**Comment by et2010** [comment]
Thanks for the tips! I'll give it a look.
